name: release

on:
  workflow_run:
    workflows:
      - test
    branches:
      - master
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: python-semantic-release/python-semantic-release@v10.7.0
        id: release
        name: Semantic Version Release
        with:
          config_file: releaserc.toml
          github_token: ${{ secrets.RELEASE_BOT_TOKEN }}

      - uses: python-semantic-release/publish-action@v10.7.0
        name: Publish GitHub Release
        if: steps.release.outputs.released == 'true'
        with:
          config_file: releaserc.toml
          github_token: ${{ secrets.RELEASE_BOT_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
